name: morpheus_common
description: Morpheus Common

version: 1.0.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # For state management
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  # Other
  intl: ^0.15.8
  json_schema: ^2.2.1
  form_field_validator: ^1.0.1
  optional: ^4.0.1
  image_picker: ^0.6.3+1
  flutter_image_compress: ^0.6.5+1
  morpheus_sdk:
    path: ../../morpheus-dart
